### ISSUE TITLE
When invalid message, it throws ENOENT error too

### ISSUE THREAD

**Issue by olstenlarck** [conventional-changelog-archived-repos/validate-commit-msg#112]
Because of no existence of `./.git/logs/incorrect-commit-msgs`
```
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
foo abr baz
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/charlike/github/koa-better-serve/.git/logs/incorrect-commit-msgs'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.fs.appendFileSync (fs.js:1345:6)
    at validate (/home/charlike/github/koa-better-serve/node_modules/validate-commit-msg/lib/cli.js:95:10)
    at Object.<anonymous> (/home/charlike/github/koa-better-serve/node_modules/validate-commit-msg/lib/cli.js:101:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by charlike** [comment]
Probably, after glance look over the code, comes from [lib/cli.js#L95](https://github.com/conventional-changelog/validate-commit-msg/blob/master/lib/cli.js#L95) and L86.

For some reason i testing it in just initialized repo.

**Comment by cmalard** [comment]
Hi @charlike :-)

>fs.appendFileSync
>Asynchronously append data to a file, creating the file if it does not yet exist

Should not be an issue :o

What's your Node version ?

**Comment by charlike** [comment]
Hm, then it's something other.

> What's your Node version ?

8.2.0

**Comment by hutson** [comment]
This package has been deprecated. Please use https://github.com/marionebl/commitlint instead.
